### PR TITLE
Implement compact hashcode

### PR DESCRIPTION
**Pull request by rkennke**
TBD

---------
### Progress
- [ ] Change must not contain extraneous whitespace
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Integration blockers
&nbsp;⚠️ Too few reviewers with at least role committer found (have 0, need at least 1) (failed with updated jcheck configuration in pull request)
&nbsp;⚠️ Whitespace errors (failed with updated jcheck configuration in pull request)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/lilliput.git pull/14/head:pull/14` \
`$ git checkout pull/14`

Update a local copy of the PR: \
`$ git checkout pull/14` \
`$ git pull https://git.openjdk.org/lilliput.git pull/14/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14`

View PR using the GUI difftool: \
`$ git pr show -t 14`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/lilliput/pull/14.diff">https://git.openjdk.org/lilliput/pull/14.diff</a>

</details>

### CODE REVIEW

**Comment by LifeIsStrange** [comment]
@rkennke Many thanks for your amazing works on project Lilliput, I am very excited to see what the future will bring :)
While Lilliput primarily targets spatial efficiency, I believe that you believe there are also opportunities for improving temporal efficiency. Hashing is a key performance task in computer engineering and there has been many major advances in state of the art hashing algorithms (and also in SIMD optimizations) the last few years.
As a consequence, the JDK hashing algorithm implementation must be very significantly slower than the State Of The Art.
It recently made the news and Linux is now using the SOTA C implementation Blake2 and allow for [370% faster dev/u/random](https://twitter.com/FiloSottile/status/1476698207413493766)
Linux however is overconservative but there is the Blake3 implementation which is [_significantly faster_](https://github.com/BLAKE3-team/BLAKE3) than Blake2.
But Blake are cryptographic hashs, since I assume that Java object identity can use non-cryptographic hashes, there are even faster advances:
The most popular benchmark comparison is:
https://github.com/rurban/smhasher#summary
Possibly the best hashing algorithm and implementation (C) seems to be XXH3
https://github.com/Cyan4973/xxHash/wiki/Performance-comparison
As such, I think it's time for the Java world to start leveraging more and more SOTA algorithms :)
And maybe that you could consider intergrating XXHash3 !

**Comment by rkennke** [comment]
> @rkennke Many thanks for your amazing works on project Lilliput, I am very excited to see what the future will bring :) While Lilliput primarily targets spatial efficiency, I believe that you believe there are also opportunities for improving temporal efficiency. Hashing is a key performance task in computer engineering and there has been many major advances in state of the art hashing algorithms (and also in SIMD optimizations) the last few years. As a consequence, the JDK hashing algorithm implementation must be very significantly slower than the State Of The Art. It recently made the news and Linux is now using the SOTA C implementation Blake2 and allow for [370% faster dev/u/random](https://twitter.com/FiloSottile/status/1476698207413493766) Linux however is overconservative but there is the Blake3 implementation which is [_significantly faster_](https://github.com/BLAKE3-team/BLAKE3) than Blake2. But Blake are cryptographic hashes, since I assume that Java object identity can use non-cryptographic hashes, there are even faster advances: The most popular benchmark comparison is: https://github.com/rurban/smhasher#summary Possibly the best hashing algorithm and implementation (C) seems to be the XXH family https://github.com/Cyan4973/xxHash/wiki/Performance-comparison As such, I think it's time for the Java world to start leveraging more and more SOTA algorithms :) And maybe that you could consider intergrating XXHash3 or XXH32 ! note: there are other "revolutionnary" SOTA advances that the JDK would benefit from, such as SIMDJSON and many other advances made by Lemire. However to me the most critical missed opportunity in the JDK is to implement SOTA hashmaps by reusing the fastest C/CPP hashmap on earth: https://abseil.io/about/design/swisstables since this data structure is a key universal bottleneck. subnote: the [inter-relation](https://lemire.me/blog/2018/03/28/when-accessing-hash-tables-how-much-time-is-spent-computing-the-hash-functions/) with hashing algorithms is interesting

Thank you for your input! In this proposed change, I am implementing the object identity hashcode using murmur3. How do the proposed XXHash3 or XXH32 compare to that? Notice that I 'only' need to hash a 64bit value (the object address) into a 32bit hash-code (at least for now - it may be nice to extend hashes to 64 or even 128 bit in the future, but not in the scope of Lilliput). And it should be fast, too, so that it can be recomputed repeatedly until the object gets displaced by the GC (if ever). Notice also that we're not messing with any other hashCode() implementations in the JDK (in the class-library).

**Comment by LifeIsStrange** [comment]
@rkennke I am deeply sorry for the late response :m
> using murmur3. How do the proposed XXHash3 or XXH32 compare to that?
Yes so since you're targeting 32bit lenght you would consider XXH32 and as you can see, where murmur3 perform 3.9 GB/s XXH32 performs 9.7 GB/s, which is significantly faster.
cf https://github.com/Cyan4973/xxHash/wiki/Performance-comparison

> Notice also that we're not messing with any other hashCode() implementations in the JDK (in the class-library).
That is unfortunate as it is what bottleneck many applications :/
Still keep up the good work, you are doing very meaningful optimizations with lilliput :)

**Comment by rkennke** [comment]
Closing in favor of #137

**Review by salasjuarezederaldair60-eng — COMMENTED** [review]
Hi @salasjuarezederaldair60-eng, thanks for making a comment in an OpenJDK project!

All comments and discussions in the OpenJDK Community must be made available under the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/). If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please Use "Add GitHub user salasjuarezederaldair60-eng" for the summary.

If you are not an OpenJDK Author, Committer or Reviewer, simply check the box below to accept the OpenJDK Terms of Use for your comments.

 - [ ]  I agree to the [OpenJDK Terms of Use](https://openjdk.java.net/legal/tou/) for all comments I make in a project in the [OpenJDK GitHub organization](https://github.com/openjdk).

Your comment will be automatically restored once you have accepted the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/).

**Pull request closed without merging**
