### PR TITLE
Merge jdk

### PR DESCRIPTION
**Pull request by tstuefe**
This merges the Lilliput Repo to whats currently on JDK head, up to and including:

```
commit e1fdef56135c2987b128884ef632b64c32dd674a (jdk-upstream/master)
Author: Tom Rodriguez <never@openjdk.org>
Date:   Wed Aug 16 06:06:59 2023 +0000

    8314324: "8311557: [JVMCI] deadlock with JVMTI thread suspension" causes various failures

```

It contains a preparatory pre-merge commit that rolls back the first prototype of 22bit nKlass IDs: a1c5f766276fe0c6782e2bf3aaaa41e0637223ad

After that, merge-induced cleanups and fixes were minimal.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/lilliput.git pull/104/head:pull/104` \
`$ git checkout pull/104`

Update a local copy of the PR: \
`$ git checkout pull/104` \
`$ git pull https://git.openjdk.org/lilliput.git pull/104/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 104`

View PR using the GUI difftool: \
`$ git pr show -t 104`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/lilliput/pull/104.diff">https://git.openjdk.org/lilliput/pull/104.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/lilliput/pull/104#issuecomment-1682116413)

### CODE REVIEW

**Comment by rkennke** [comment]
I believe you need to change the title to just 'Merge jdk' if you merge from jdk head, or 'Merge jdk:$TAG' if you want to merge specific tag (See e.g. #94 or #97). Then please go ahead and integrate!

**Comment by tstuefe** [comment]
> I believe you need to change the title to just 'Merge jdk' if you merge from jdk head, or 'Merge jdk:$TAG' if you want to merge specific tag (See e.g. #94 or #97). Then please go ahead and integrate!

Okay, thanks.

Some tests fail though. All the new tests added for GenZ, hehe, they deadlock. I first thought this had to do with 8311981, but it still happens with Davids fix.

Should I integrate nevertheless?

**Comment by rkennke** [comment]
> > I believe you need to change the title to just 'Merge jdk' if you merge from jdk head, or 'Merge jdk:$TAG' if you want to merge specific tag (See e.g. #94 or #97). Then please go ahead and integrate!
> 
> Okay, thanks.
> 
> Some tests fail though. All the new tests added for GenZ, hehe, they deadlock. I first thought this had to do with 8311981, but it still happens with Davids fix.
> 
> Should I integrate nevertheless?

Are the failures only in Lilliput repo, or do they also deadlock in upstream?

**Comment by shipilev** [comment]
gc/stringdedup/ timeouts with GenZ look like: 
  https://bugs.openjdk.org/browse/JDK-8311981

I wonder if every other failure is actually the manifestation of that one. Can you pick up another merge from master easily? If not, I would be okay with pushing the merge as is, and then dealing with the test failures separately, possibly with another merge.

**Comment by tstuefe** [comment]
> gc/stringdedup/ timeouts with GenZ look like: https://bugs.openjdk.org/browse/JDK-8311981
> 
> I wonder if every other failure is actually the manifestation of that one. Can you pick up another merge from master easily? 

This is already with Davids fix. It only fails on Lilliput, not in head.

I only see timeouts with compiler enabled (both c1 and c2). No errors with Xint.

I tested with LockingMode 0 (HeavyMonitors) and 1 (default), all the same.

I debugged the app, but could see no obvious deadlock. All relevant threads were waiting on unowned monitors.

> If not, I would be okay with pushing the merge as is, and then dealing with the test failures separately, possibly with another merge.

Okay, will do that.

**Pull request closed without merging**
