### PR TITLE
8307392: [Lilliput] Revert deflation of dead object's monitors

### PR DESCRIPTION
**Pull request by rkennke**
In https://github.com/openjdk/lilliput/pull/28, I introduced some code that forces deflation of monitors on objects that are about to die. Discussions around a possible upstreaming of this code (https://github.com/openjdk/jdk/pull/13721) comes to the conclusion that this should not be necessary, and indeed, I could not reproduce the original problem that I was having in Lilliput with the code removed. I assume some changes in upstream and/or Lilliput since then have fixed the root cause. Let's remove that code and see what explodes.

Testing: (All with -XX:+UseHeavyMonitors to amplify monitor traffic)
 - [x] hotspot_gc
 - [x] tier1
 - [x] tier2
 - [x] SPECjvm workloads

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [JDK-8307392](https://bugs.openjdk.org/browse/JDK-8307392): [Lilliput] Revert deflation of dead object's monitors

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/lilliput.git pull/88/head:pull/88` \
`$ git checkout pull/88`

Update a local copy of the PR: \
`$ git checkout pull/88` \
`$ git pull https://git.openjdk.org/lilliput.git pull/88/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 88`

View PR using the GUI difftool: \
`$ git pr show -t 88`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/lilliput/pull/88.diff">https://git.openjdk.org/lilliput/pull/88.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/lilliput/pull/88#issuecomment-1533619413)

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
But we know this would not be safe without the GC threads rendezvous-ing, right? Also, this seems to include #90.

**Comment by rkennke** [comment]
> But we know this would not be safe without the GC threads rendezvous-ing, right? Also, this seems to include #90.

Yes, but in Lilliput we rendezous GC threads since #27. This PR essentially reverts that earlier PR. I removed the Shenandoah part.

**Review by shipilev — APPROVED** [review]
Okay then!

**Pull request closed without merging**
