### PR TITLE
Implement ZGC support

### PR DESCRIPTION
**Pull request by rkennke**
This change enables support for ZGC in Lilliput.

Similar to Shenandoah, the main trouble is concurrent relocation racing with stack-locking while trying to get hold of the header to figure out the object size. See #32 for details on this. Unfortunately, unlike Shenandoah, we cannot use the header as arbiter to prevent that race, because ZGC uses a forwarding table instead. For this reason I disabled stack-locking with ZGC, for now.

Other changes:
- Plant some STS usage, this is important to avoid racing header acess in GC workers with concurrent monitor deflation. Especially the ZRelocationTask and ZMarkTask don't seem to run under STS, and ZMarkRootTask has an STSJoiner in its constructor, but that would be called by the thread that drives the workers, not by the worker thread itself. I moved it into the worker. I also planted STS::yield() calls, so that safepoints (e.g. for monitor cleanup) can be reached in a timely manner. It may be useful to not do that after every object, but only after a certain number of strides, but that seems a minor and secondary problem.
- Removed an assert in ZBarrierSetC2 that seems wrong under Lilliput.

Testing:
 - [x] gc/z
 - [x] tier1 +UseZGC
 - [ ] tier2 +UseZGC
 - [ ] tier3 +UseZGC

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Erik Österlund](https://openjdk.java.net/census#eosterlund) (@fisk - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/lilliput pull/44/head:pull/44` \
`$ git checkout pull/44`

Update a local copy of the PR: \
`$ git checkout pull/44` \
`$ git pull https://git.openjdk.java.net/lilliput pull/44/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 44`

View PR using the GUI difftool: \
`$ git pr show -t 44`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/lilliput/pull/44.diff">https://git.openjdk.java.net/lilliput/pull/44.diff</a>

</details>

### CODE REVIEW

**Review by fisk — APPROVED** [review]
Looks good.

**Comment by rkennke** [comment]
> Looks good.

Thanks, Erik.

However, I am back-paddling a little bit. Putting the STS in concurrent marking seems to break a number of tests. I am not quite sure why, though. OTOH, I believe it is necessary to do the STS during marking, because marking needs to access the Klass* (for object layout), and this needs be be safe wrt monitor deflation. I am investigating.

**Comment by fisk** [comment]
> > Looks good.
> 
> Thanks, Erik.
> 
> However, I am back-paddling a little bit. Putting the STS in concurrent marking seems to break a number of tests. I am not quite sure why, though. OTOH, I believe it is necessary to do the STS during marking, because marking needs to access the Klass* (for object layout), and this needs be be safe wrt monitor deflation. I am investigating.

Generational ZGC already uses STS in these places (and a super special homegrown STS mechanism for relocation). I don't recall exactly what issues we ran into migrating the code to do that. :/

**Review by fisk — APPROVED** [review]
Looks good. Probably possible to get some deadlocks when in-place relocation is triggered from a load barrier in a safepoint, but we can deal with that separately.

**Comment by rkennke** [comment]
Thanks, Erik!

/integrate

**Pull request closed without merging**
