### PR TITLE
Fix loading Klass* in C1 on AArch64

### PR DESCRIPTION
**Pull request by rkennke**
PR #20 was not quite correct on AArch64:
- We cannot push/pop r0 in the code stub, because we must not mess with SP there, otherwise the argument passing does not work.
- We should use far_call() and not far_jump(), so that the return comes back into the stub, and not to the continuation (or whereever LR points to).

Testing:
 - [x] tier1
 - [x] tier2
 - [x] tier3

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Aleksey Shipilev](https://openjdk.java.net/census#shade) (@shipilev - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/lilliput pull/34/head:pull/34` \
`$ git checkout pull/34`

Update a local copy of the PR: \
`$ git checkout pull/34` \
`$ git pull https://git.openjdk.java.net/lilliput pull/34/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 34`

View PR using the GUI difftool: \
`$ git pr show -t 34`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/lilliput/pull/34.diff">https://git.openjdk.java.net/lilliput/pull/34.diff</a>

</details>

### CODE REVIEW

**Comment by rkennke** [comment]
@shipilev @adinn or @aph could you have a look, please?

**Review by shipilev — COMMENTED** [review]
Why this new stub is different, i.e. why can it return not in `r0`? I am looking at e.g. `NewObjectArrayStub::emit_code`, and it has `assert(_result->as_register() == r0, "result must in r0");`. In fact, I cannot see any stub call with `far_call` that saves the registers itself...

**Comment by rkennke** [comment]
> Why this new stub is different, i.e. why can it return not in `r0`? I am looking at e.g. `NewObjectArrayStub::emit_code`, and it has `assert(_result->as_register() == r0, "result must in r0");`. In fact, I cannot see any stub call with `far_call` that saves the registers itself...

The most correct way to do it would be to tell C1 to allocate the result register in r0. I tried that. However, it doesn't work with the code here:
https://github.com/openjdk/lilliput/blob/master/src/hotspot/share/gc/shared/c1/barrierSetC1.cpp#L337

Mostly because there is control flow (that probably shouldn't be there) and that confuses the register allocator.

**Comment by theRealAph** [comment]
This doesn't look right. There's no point saving anything in res, because it may well just get clobbered by `Runtime1::load_klass_id`. Like Aleksey, I can't see why forcing res into `r0` won't work.

**Comment by rkennke** [comment]
> This doesn't look right. There's no point saving anything in res, because it may well just get clobbered by `Runtime1::load_klass_id`. Like Aleksey, I can't see why forcing res into `r0` won't work.

I agree, and I would prefer to register-allocate res in r0. I tried that, and it works in most cases, but unfortunately C1 fails to do that correctly in this code sequence:
https://github.com/openjdk/lilliput/blob/master/src/hotspot/share/gc/shared/c1/barrierSetC1.cpp#L337

The reason for that is (according to @rwestrel) that the code sequence contains control flow inside a single basic block (which is borderline illegal, and we kinda lucky that it doesn't blow up), and that confuses the register allocator and would end up clobbering some other value. Fixing this would require to rewrite that code sequence to either emit several basic blocks and stitch together the control flow correctly. I don't really want to go there :-)

What I'm doing instead is allocate res freely, and then shuffle registers accordingly in the backend. What I'm doing here is this:
1. If res is allocated in r0 we don't have a problem at all, and don't need to do anything.
2. Else, I swap r0 and res. This preserves the original contents of r0 in res, which will be preserved around the call. This frees r0 for use as argument and result register.
3. After the call, I swap r0 and res again: This brings the result into res, and restores the original value of r0 from res (which has been push/popped around the call).

**Comment by theRealAph** [comment]
>     1. If res is allocated in r0 we don't have a problem at all, and don't need to do anything.
> 
>     2. Else, I swap r0 and res. This preserves the original contents of r0 in res, which will be preserved around the call. This frees r0 for use as argument and result register.

Why will res be preserved around the call? That's the part I don't get.

**Comment by rkennke** [comment]
> > ```
> > 1. If res is allocated in r0 we don't have a problem at all, and don't need to do anything.
> > 
> > 2. Else, I swap r0 and res. This preserves the original contents of r0 in res, which will be preserved around the call. This frees r0 for use as argument and result register.
> > ```
> 
> Why will res be preserved around the call? That's the part I don't get.

Because I implemented it that way (just like most other runtime call stubs):
https://github.com/openjdk/lilliput/blob/a9ec867aea4d665a1fc85f51bdb7586a575fcdcf/src/hotspot/cpu/aarch64/c1_Runtime1_aarch64.cpp#L725

**Comment by theRealAph** [comment]
Ahh, I see. OK, it's kinda horrible, but I guess it'll be fixed later.

**Comment by rkennke** [comment]
> Ahh, I see. OK, it's kinda horrible,

It's C1 :-/

> but I guess it'll be fixed later.

Famous last words :-D

**Comment by rkennke** [comment]
> Ahh, I see. OK, it's kinda horrible, but I guess it'll be fixed later.

@shipilev is that ok for you too?

**Review by shipilev — APPROVED** [review]
OK, after reading the discussion, I understand what is going on here. Approving, but flickering through the horror-awe-disgust-amuzement cycle real hard here. :)

**Pull request closed without merging**
